{% set name = "sundials" %}
{% set version = "6.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 43cc11bf9ee1765cb1a600b8ba5a439ccf6f1e9163f7ba6868a146f9f51dbcba

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('sundials', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make   # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas  # [not win]
    - liblapack  # [not win]
    - suitesparse  # [not win]
  run:
    - suitesparse  # [not win]

test:
  commands:
    - test -f ${PREFIX}/include/sundials/sundials_band.h  # [unix]

about:
  home: http://computation.llnl.gov/casc/sundials/main.html
  license: BSD-3-Clause
  license_file: LICENSE
  summary: SUite of Nonlinear and DIfferential/ALgebraic equation Solvers

extra:
  recipe-maintainers:
    - bjodah
    - jschueller
