{% set name = "sundials" %}
{% set version = "5.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://computation.llnl.gov/projects/{{ name }}/download/{{ name }}-{{ version }}.tar.gz
  sha256: 04d8a2ebe02cdaeef5a9e22ff7e3146bb563d8400f65772b6c7af80001413ffa

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('sundials', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make   # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and vc<14]
    - liblapack  # [not win]
    - suitesparse  # [not win]
  run:
    - suitesparse  # [not win]

test:
  requires:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  files:
    - CMakeLists.txt
    - cvRoberts_dns.c
    - cvRoberts_klu.c
    - cvAdvDiff_bndL.c
    - cvAdvDiff_bnd_omp.c

about:
  home: http://computation.llnl.gov/casc/sundials/main.html
  license: BSD-3-Clause
  license_file: LICENSE
  summary: SUite of Nonlinear and DIfferential/ALgebraic equation Solvers

extra:
  recipe-maintainers:
    - bjodah
    - jschueller
