{% set name = "sundials" %}
{% set version = "6.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3cbf0102c3284dc550a9faf85ace030ca6d02fe70e90afa2d0d8074a098a3948

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('sundials', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make   # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas  # [not win]
    - liblapack  # [not win]
    - suitesparse  # [not win]
  run:
    - suitesparse  # [not win]

test:
  commands:
    - test -f ${PREFIX}/include/sundials/sundials_band.h  # [unix]

about:
  home: https://computing.llnl.gov/projects/sundials
  license: BSD-3-Clause
  license_file: LICENSE
  summary: SUite of Nonlinear and DIfferential/ALgebraic equation Solvers

extra:
  recipe-maintainers:
    - bjodah
    - jschueller
