{% set name = "sundials" %}
{% set version = "3.0.0" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://computation.llnl.gov/projects/{{ name }}/download/{{ name }}-{{ version }}.tar.gz
  sha256: 28b8e07eecfdef66e2c0d0ea0cb1b91af6e4e94d71008abfe80c27bf39f63fde

build:
  number: 0
  features:
    - blas_{{ variant }}  # [not win]
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]
  skip: true  # [win and py>35]

requirements:
  build:
    - cmake
    - msinttypes  # [win and py<35]
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19|0.2.19.*  # [not win]
    - suitesparse  # [not win]
    - python  # [win]
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19|0.2.19.*  # [not win]
    - suitesparse  # [not win]

test:
  requires:
    - cmake
    - python  # [win]
  files:
    - cvRoberts_dns.c

about:
  home: http://computation.llnl.gov/casc/sundials/main.html
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'SUite of Nonlinear and DIfferential/ALgebraic equation Solvers'

extra:
  recipe-maintainers:
    - bjodah
    - jschueller
