{% set name = "sundials" %}
{% set version = "6.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f368abc99da305da0b1bc64386d350023d7c5ba2d5c689eee36cd7846e3096d1

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('sundials', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make   # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas  # [not win]
    - liblapack  # [not win]
    - suitesparse  # [not win]
  run:
    - suitesparse  # [not win]

test:
  commands:
    - test -f ${PREFIX}/include/sundials/sundials_band.h  # [unix]

about:
  home: https://computing.llnl.gov/projects/sundials
  license: BSD-3-Clause
  license_file: LICENSE
  summary: SUite of Nonlinear and DIfferential/ALgebraic equation Solvers

extra:
  recipe-maintainers:
    - bjodah
    - jschueller
