travis:
  secure:
    BINSTAR_TOKEN: Y1BQo+tuE2GInHoJ1sRM/t6rCPoxIREfdKc7sCXkbZsAbTb0YKsnWb+1YHUShNm5jwRCfqQc5TAckCU9l7PwLsAlyPakbY7utUtDsx6O2mEqi5BgWANxmvuEl8LVLXsQm0GjqFybUQmIgihSFhD+PdKfPa2X2NFDlehkBHzswptfroBa2RJJc9KPKzyboorCVPTQfCrnce6ls0wvnDoqPAF7AAc3emv64XpEIgC6VQMpDDlgPCq5kql7E87+IP8RXe23zNfbpCc28A/hNCzRiUhZaDL0c9nfn1fiSfLmVgCMG5g9n2dGGXjzf2wyP77et6Iw8TDKwoGD38ww9H4zfDoWeDCAe8p/CKEGjmz9YL4BSaqKr0yuE+LG3RKifnrPvSg4Wysh+i1ORyzCBTpBWlThls9RVyeje47JbQ9nDqLLytE6dqtJIP8z/laVsExIMbCTfovOKmKlX53wCihEVOuxQhIkG3wZ2x7ilVkZ5ijErD8+LR9KTQROH6fpEBDdmUUwaHngrMuSdrLLpkcc8wEullJxOOwAG1wkrzBRDAugygOzB47q7iOY1yBfgOnIOKMNWTXml4S2HVOKa1gtTmUjTmt7oHvc+Wry6c8Hf/I2lPloIEfiaMwTsTYm0VORdbbWNF3142tVgKt2bZxnaIJveaF5DLsDHy6qKgMBCVE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
